### ISSUE TITLE
can't run `docker-compose up -d --build `

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#1419]
```
kevinowocki@local /Users/kevinowocki/Sites/gitcoin/web~ % docker-compose down; docker-compose up -d --build     (git)-[master] :2f4i1d
Stopping web_pgweb_1 ... done
Stopping web_web_1   ... done
Stopping web_db_1    ... done
Removing web_pgweb_1   ... done
Removing web_web_1     ... done
Removing web_testrpc_1 ... done
Removing web_db_1      ... done
Removing web_node_1    ... done
Removing network web_default
Creating network "web_default" with the default driver
Building web
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1052, in up
  File "compose/cli/main.py", line 1048, in up
  File "compose/project.py", line 466, in up
  File "compose/service.py", line 329, in ensure_image_exists
  File "compose/service.py", line 1047, in build
  File "site-packages/docker/api/build.py", line 154, in build
  File "site-packages/docker/utils/build.py", line 31, in tar
  File "site-packages/docker/utils/build.py", line 162, in create_archive
  File "tarfile.py", line 1802, in gettarinfo
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kevinowocki/Sites/gitcoin/web/app/assets/v2/js/pages/tokens_settings.js'
[1209] Failed to execute script docker-compose

```

**Comment by owocki** [comment]
nevermind it seems to just have been an intermittent issue
