### ISSUE TITLE
Ratelimited

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#1455]
View details in Rollbar: [https://rollbar.com/gitcoin/gitcoin/items/1320/](https://rollbar.com/gitcoin/gitcoin/items/1320/)

```
Traceback (most recent call last):
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/ratelimit/decorators.py", line 29, in _wrapped
    raise Ratelimited()
Ratelimited
```

**Comment by owocki** [comment]
hmmm this was me.. sending a bunch of tips.  

where do i go to remove the rate limit?  django or nginx?
