### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#1503]
View details in Rollbar: [https://rollbar.com/gitcoin/gitcoin/items/1366/](https://rollbar.com/gitcoin/gitcoin/items/1366/)

```
Traceback (most recent call last):
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/gitcoin/coin/app/faucet/views.py", line 107, in process_faucet_request
    faucet_amount = float(settings.FAUCET_AMOUNT) * float(recommend_min_gas_price_to_confirm_in_time(5))
TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'
```

**Comment by owocki** [comment]
i dont get it.  this is pretty explicitly cast to a float
