### ISSUE TITLE
StatusError: HTTPError: 504 Server Error: GATEWAY_TIMEOUT for url: https://ipfs.gitcoin.co:443/api/v0/cat?stream-channels=true&arg=QmNk3CfMScMut3kcFKP7DMCV1y1ZF99D8N3hNZ1bmGqj2T

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#1819]
View details in Rollbar: [https://rollbar.com/gitcoin/gitcoin/items/1724/](https://rollbar.com/gitcoin/gitcoin/items/1724/)

```
Traceback (most recent call last):
  File "/home/ubuntu/gitcoin/coin/app/dashboard/management/commands/sync_geth.py", line 62, in handle
    bounty = get_bounty(bounty_enum, network)
  File "/home/ubuntu/gitcoin/coin/app/dashboard/utils.py", line 242, in get_bounty
    bounty_data_str = ipfs_cat(bountydata)
  File "/home/ubuntu/gitcoin/coin/app/dashboard/utils.py", line 163, in ipfs_cat
    response = ipfs_cat_ipfsapi(key)
  File "/home/ubuntu/gitcoin/coin/app/dashboard/utils.py", line 180, in ipfs_cat_ipfsapi
    return ipfs.cat(key)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/ipfsapi/client.py", line 201, in cat
    return self._client.request('/cat', args, **kwargs)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/ipfsapi/http.py", line 37, in wrapper
    return func(self, *args, **merged)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/ipfsapi/http.py", line 170, in request
    files, headers, data)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/ipfsapi/http.py", line 120, in _request
    self._do_raise_for_status(res, ret)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/ipfsapi/http.py", line 94, in _do_raise_for_status
    six.raise_from(exceptions.StatusError(error), error)
  File "<string>", line 3, in raise_from
StatusError: HTTPError: 504 Server Error: GATEWAY_TIMEOUT for url: https://ipfs.gitcoin.co:443/api/v0/cat?stream-channels=true&arg=Qmd41jfHhnuc4pQd1yB1m5qUXQfKfwBDjFWXZKYkqoKM4qTraceback (most recent call last):
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/ipfsapi/http.py", line 85, in _do_raise_for_status
    response.raise_for_status()
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 504 Server Error: GATEWAY_TIMEOUT for url: https://ipfs.gitcoin.co:443/api/v0/cat?stream-channels=true&arg=Qmd41jfHhnuc4pQd1yB1m5qUXQfKfwBDjFWXZKYkqoKM4q
```

**Comment by mbeacom** [comment]
I was messing with geth nodes on the same k8s cluster as ipfs which led to a spike before scaling out - Resolved now.
