### ISSUE TITLE
KUDOS: SyntaxError: Unexpected token } in JSON at position 19

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#2554]
https://sentry.gitcoin.co/gitcoin/gitcoin-prod-frontend/issues/1617/

```
SyntaxError: Unexpected token } in JSON at position 19
  at JSON.parse (<anonymous>)
  at getQueryParams (/static/v2/js/pages/kudos-search.0f78e39d05e9.js:33:15)
  at HTMLDocument.<anonymous> (/static/v2/js/pages/kudos-search.0f78e39d05e9.js:4:20)
  at j (/static/v2/js/jquery.c9f5aeeca3ad.js:2:29999)
  at k (/static/v2/js/jquery.c9f5aeeca3ad.js:2:30313)
...
(1 additional frame(s) were not displayed)
```

**Comment by jasonrhaas** [comment]
@mbeacom Can you give me and @octavioamu access to sentry so we can take a look at the issue references?

**Comment by octavioamu** [comment]
I will take a look on this one
