### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#361]
View details in Rollbar: [https://rollbar.com/mbeacom/gitcoin/items/160/](https://rollbar.com/mbeacom/gitcoin/items/160/)

```
Traceback (most recent call last):
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/ratelimit/decorators.py", line 30, in _wrapped
    return fn(*args, **kw)
  File "/home/ubuntu/gitcoin/coin/app/dashboard/views.py", line 569, in sync_web3
    bountydetails, issueURL, contract_address, network)
  File "/home/ubuntu/gitcoin/coin/app/dashboard/helpers.py", line 245, in process_bounty_details
    bountyDataPayload = bountyData.get('payload', {})
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by mbeacom** [comment]
Temporarily resolved in: https://github.com/gitcoinco/web/commit/f9751f692f41dda8e21bd76226da9d65ffee843f
