### ISSUE TITLE
errors upon trying to deploy

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3809]
```
  File "./manage.py", line 59, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/home/ubuntu/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/home/ubuntu/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/ubuntu/gitcoin/gitcoin-37/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/gitcoin/coin/app/app/settings.py", line 340, in <module>
    if LOGGING:
KeyError: 'root'
```

AND

```
(gitcoin-37) ubuntu@ip-172-31-1-57:~/gitcoin/coin/app$ ./manage.py migrate
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/config.py", line 555, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.7/logging/config.py", line 705, in configure_handler
    klass = self.resolve(cname)
  File "/usr/lib/python3.7/logging/config.py", line 375, in resolve
    found = self.importer(used)
ValueError: Empty module name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 59, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/ubuntu/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/ubuntu/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.7/logging/config.py", line 792, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.7/logging/config.py", line 563, in configure
    '%r' % name) from e
ValueError: Unable to configure handler 'console'
```
AND

```
(gitcoin-37) ubuntu@ip-172-31-1-57:~/gitcoin/coin/app$ ./manage.py migrate
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/config.py", line 555, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.7/logging/config.py", line 705, in configure_handler
    klass = self.resolve(cname)
  File "/usr/lib/python3.7/logging/config.py", line 375, in resolve
    found = self.importer(used)
ValueError: Empty module name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 59, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/ubuntu/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/ubuntu/gitcoin/gitcoin-37/lib/python3.7/site-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.7/logging/config.py", line 792, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.7/logging/config.py", line 563, in configure
    '%r' % name) from e
ValueError: Unable to configure handler 'console'
```

**Comment by owocki** [comment]
@danlipert is there any fix it twice for this, or does the stopgap work suffiicently?

**Comment by danlipert** [comment]
@owocki I have a WIP PR to make this look a bit nicer, plus work for prod and local deploys, with or without sentry: https://github.com/gitcoinco/web/pull/3837 I just want to do some final testing and then it should be good to go
