### ISSUE TITLE
'manage.py migrate' fails locally

### ISSUE THREAD

**Issue by oddballbutler** [gitcoinco/web#4669]
I'm having problems running migrations locally on docker after pulling latest from Master

Here's the command output:
```
docker-compose exec web python3 app/manage.py migrate
WARNING: The TEST_MNEMONIC variable is not set. Defaulting to a blank string.
WARNING: Some services (db, ipfs, redis, testrpc, web) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
/code/app/dashboard/utils.py:27: FutureWarning: The `ipfsapi` library is deprecated and will stop receiving updates on the 31.12.2019! If you are on Python 3.5+ please enable and fix all Python deprecation warnings (CPython flag `-Wd`) and switch to the new `ipfshttpclient` library name. Python 2.7 and 3.4 will not be supported by the new library, so please upgrade.
  import ipfsapi
Operations to perform:
  Apply all migrations: admin, auth, avatar, bounty_requests, contenttypes, dashboard, dataviz, db, easy_thumbnails, economy, enssubdomain, event_ethdenver2019, faucet, gas, gitcoinbot, grants, impersonate, inbox, kudos, linkshortener, marketing, perftools, revenue, sessions, sites, social_django, tdi
Running migrations:
  Applying dashboard.0002_auto_20181226_1716...Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DuplicateColumn: column "preferred_kudos_wallet_id" of relation "dashboard_profile" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app/manage.py", line 59, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 84, in database_forwards
    field,
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 435, in add_field
    self.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 133, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/cacheops/transaction.py", line 99, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "preferred_kudos_wallet_id" of relation "dashboard_profile" already exists
```
I have tried removing all the docker images and containers and starting over, but still no dice.

**Comment by thelostone-mc** [comment]
hmm could we try it once again with `docker-compose -v`  followed by `docker-compose up`
I just tested it against `master` and it works fine

**Comment by oddballbutler** [comment]
@thelostone-mc 
```
jeremy@jeremyDesktop:~/github/gitcoin_web$ docker-compose -v
docker-compose version 1.23.2, build 1110ad01
jeremy@jeremyDesktop:~/github/gitcoin_web$ docker-compose up
WARNING: The TEST_MNEMONIC variable is not set. Defaulting to a blank string.
WARNING: Some services (db, ipfs, redis, testrpc, web) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Starting gitcoin_web_testrpc_1 ... done
Starting gitcoin_web_ipfs_1    ... done
Starting gitcoin_web_redis_1   ... done
Starting gitcoin_web_db_1      ... done
Starting gitcoin_web_web_1     ... done
Attaching to gitcoin_web_testrpc_1, gitcoin_web_db_1, gitcoin_web_redis_1, gitcoin_web_ipfs_1, gitcoin_web_web_1
db_1       | 2019-06-23 01:00:28.907 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1       | 2019-06-23 01:00:28.907 UTC [1] LOG:  listening on IPv6 address "::", port 5432
testrpc_1  | Ganache CLI v6.4.4 (ganache-core: 2.5.6)
testrpc_1  | (node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
db_1       | 2019-06-23 01:00:28.918 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
redis_1    | 1:C 23 Jun 01:00:29.773 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1    | 1:C 23 Jun 01:00:29.773 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
testrpc_1  | 
testrpc_1  | Available Accounts
testrpc_1  | ==================
ipfs_1     | Changing user to ipfs
db_1       | 2019-06-23 01:00:28.951 UTC [18] LOG:  database system was shut down at 2019-06-23 01:00:00 UTC
testrpc_1  | (0) 0xe0a68584111d702a141becb6692631f1dae4711f (~100 ETH)
testrpc_1  | 
ipfs_1     | ipfs version 0.4.21
testrpc_1  | Private Keys
testrpc_1  | ==================
ipfs_1     | Found IPFS fs-repo at /data/ipfs
redis_1    | 1:C 23 Jun 01:00:29.773 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1    | 1:M 23 Jun 01:00:29.774 * Running mode=standalone, port=6379.
db_1       | 2019-06-23 01:00:28.963 UTC [1] LOG:  database system is ready to accept connections
ipfs_1     | Initializing daemon...
ipfs_1     | go-ipfs version: 0.4.21-
ipfs_1     | Repo version: 7
ipfs_1     | System version: amd64/linux
ipfs_1     | Golang version: go1.12.5
testrpc_1  | (0) 0x91938cb45eb51f9480246b3c88d82ff6a830f3328d3237997d8bb0210c07cb24
testrpc_1  | 
redis_1    | 1:M 23 Jun 01:00:29.774 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1    | 1:M 23 Jun 01:00:29.774 # Server initialized
redis_1    | 1:M 23 Jun 01:00:29.774 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1    | 1:M 23 Jun 01:00:29.774 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
testrpc_1  | HD Wallet
testrpc_1  | ==================
testrpc_1  | Mnemonic:      rent where reveal first bunker hazard among strong idea risk life left
testrpc_1  | Base HD Path:  m/44'/60'/0'/0/{account_index}
testrpc_1  | 
testrpc_1  | Gas Price
testrpc_1  | ==================
testrpc_1  | 20000000000
testrpc_1  | 
testrpc_1  | Gas Limit
testrpc_1  | ==================
testrpc_1  | 6721975
redis_1    | 1:M 23 Jun 01:00:29.774 * DB loaded from disk: 0.000 seconds
redis_1    | 1:M 23 Jun 01:00:29.774 * Ready to accept connections
testrpc_1  | 
testrpc_1  | Listening on 0.0.0.0:8545
web_1      | Requirement already satisfied: ptvsd in /usr/local/lib/python3.7/site-packages (4.2.10)
ipfs_1     | Swarm listening on /ip4/127.0.0.1/tcp/4001
ipfs_1     | Swarm listening on /ip4/172.18.0.3/tcp/4001
ipfs_1     | Swarm listening on /p2p-circuit
ipfs_1     | Swarm announcing /ip4/127.0.0.1/tcp/4001
ipfs_1     | Swarm announcing /ip4/172.18.0.3/tcp/4001
ipfs_1     | API server listening on /ip4/0.0.0.0/tcp/5001
ipfs_1     | WebUI: http://0.0.0.0:5001/webui
ipfs_1     | Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080
ipfs_1     | Daemon is ready
web_1      | VSCode remote debugger enabled! This has disabled threading!
web_1      | /code/app/dashboard/utils.py:27: FutureWarning: The `ipfsapi` library is deprecated and will stop receiving updates on the 31.12.2019! If you are on Python 3.5+ please enable and fix all Python deprecation warnings (CPython flag `-Wd`) and switch to the new `ipfshttpclient` library name. Python 2.7 and 3.4 will not be supported by the new library, so please upgrade.
web_1      |   import ipfsapi
web_1      | /usr/local/lib/python3.7/site-packages/werkzeug/datastructures.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
web_1      |   from collections import Container, Iterable, MutableSet
web_1      | /usr/local/lib/python3.7/site-packages/werkzeug/datastructures.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
web_1      |   from collections import Container, Iterable, MutableSet
web_1      | 
web_1      | You have 97 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): avatar, bounty_requests, dashboard, event_ethdenver2019, gitcoinbot, grants, inbox, kudos, marketing.
web_1      | Run 'python manage.py migrate' to apply them.
web_1      | 
web_1      |  * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
web_1      |  * Restarting with inotify reloader
web_1      | /code/app/dashboard/utils.py:27: FutureWarning: The `ipfsapi` library is deprecated and will stop receiving updates on the 31.12.2019! If you are on Python 3.5+ please enable and fix all Python deprecation warnings (CPython flag `-Wd`) and switch to the new `ipfshttpclient` library name. Python 2.7 and 3.4 will not be supported by the new library, so please upgrade.
web_1      |   import ipfsapi
web_1      | /usr/local/lib/python3.7/site-packages/werkzeug/datastructures.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
web_1      |   from collections import Container, Iterable, MutableSet
web_1      | /usr/local/lib/python3.7/site-packages/werkzeug/datastructures.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
web_1      |   from collections import Container, Iterable, MutableSet
web_1      | Performing system checks...
web_1      | 
web_1      | System check identified no issues (0 silenced).
web_1      | 
web_1      | You have 97 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): avatar, bounty_requests, dashboard, event_ethdenver2019, gitcoinbot, grants, inbox, kudos, marketing.
web_1      | Run 'python manage.py migrate' to apply them.
web_1      | 
web_1      | 
web_1      | Django version 2.1.7, using settings 'app.settings'
web_1      | Development server is running at http://0.0.0.0:8000/
web_1      | Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
web_1      | Quit the server with CONTROL-C.
web_1      |  * Debugger is active!
web_1      |  * Debugger PIN disabled.  DEBUGGER UNSECURED!

```

**Comment by thelostone-mc** [comment]
^my bad `docker-compose down -v` + `docker-compose up`

**Comment by oddballbutler** [comment]
@thelostone-mc That did the trick! Thanks!
