### ISSUE TITLE
firstly setup env for develop gitcoin with docker , failed

### ISSUE THREAD

**Issue by xiaods** [gitcoinco/web#5977]
**Describe the bug**

follow docs for [Running Locally with Docker (Recommended)](https://docs.gitcoin.co/mk_setup/)
it failed by start the web.

**To Reproduce**

1. git clone https://github.com/gitcoinco/web.git
cd web
cp app/app/local.env app/app/.env
2. docker-compose up --build
it failed :
```
Digest: sha256:fdf40555fbee6a23c2e2778312112b376a6bd68ba5961929013a472dd614a69d
Status: Downloaded newer image for ipfs/go-ipfs:release
Building web
Traceback (most recent call last):
  File "site-packages/docker/credentials/store.py", line 80, in _execute
  File "subprocess.py", line 395, in check_output
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-desktop', 'get']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/auth.py", line 264, in _resolve_authconfig_credstore
  File "site-packages/docker/credentials/store.py", line 35, in get
  File "site-packages/docker/credentials/store.py", line 93, in _execute
docker.credentials.errors.StoreError: Credentials store docker-credential-desktop exited with "error getting credentials - err: exit status 1, out: `no hostname in URL`".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1106, in up
  File "compose/cli/main.py", line 1102, in up
  File "compose/project.py", line 542, in up
  File "compose/service.py", line 350, in ensure_image_exists
  File "compose/service.py", line 1104, in build
  File "site-packages/docker/api/build.py", line 261, in build
  File "site-packages/docker/api/build.py", line 308, in _set_auth_headers
  File "site-packages/docker/auth.py", line 304, in get_all_credentials
  File "site-packages/docker/auth.py", line 281, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "error getting credentials - err: exit status 1, out: `no hostname in URL`".')
[56418] Failed to execute script docker-compose
```

**Expected behavior**

it works like a charm.

**Screenshots**

**Desktop (please complete the following information):**

- OS:   MacOs
```
$ docker --version                                                                                                                                                        [44/338]
Docker version 19.03.4, build 9013bf5
xiaods at xiaodeshi in ~/Documents/code/gitcoin-web on  (master)
$ docker-compose --version 
docker-compose version 1.25.0-rc4, build 8f3c9c58
```

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by xiaods** [comment]
force use buildkit, which does not invoke docker-credential helper without arguments:

$ COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up -d --build

it fix the bug.
