### ISSUE TITLE
sync_geth not working for bounties - local docker - rinkeby

### ISSUE THREAD

**Issue by walidmujahid** [gitcoinco/web#6353]
When trying to sync with bounties using:

`docker-compose exec web python3 app/manage.py sync_geth rinkeby -20 99999999999`

I am receving `requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://rinkeby.infura.io/`. Thinking it might be the infura ID may have expired, I supplied a custom override forINFURA_V3_PROJECT_ID, but I received the same error.

Trying: 

`docker-compose exec web python3 app/manage.py sync_geth rinkeby 1 99999999999`

I recieve the same error including a ` Failed to fetch github username` error.

Rebuilding the containers or restarting docker also does not resolve the issue.

Full Traceback for `docker-compose exec web python3 app/manage.py sync_geth rinkeby -20 99999999999`:

```WARNING: Some services (chat, db, ipfs, redis, testrpc, web) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
/usr/local/lib/python3.6/dist-packages/sorl/thumbnail/conf/__init__.py:16: RemovedInDjango30Warning: The DEFAULT_CONTENT_TYPE setting is deprecated.
  setattr(self, attr, getattr(obj, attr))
Traceback (most recent call last):
  File "app/manage.py", line 59, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/code/app/dashboard/management/commands/sync_geth.py", line 71, in handle
    start_id = get_bounty_id(options['start_id'], network)
  File "/code/app/dashboard/management/commands/sync_geth.py", line 41, in get_bounty_id
    bounty_id = contract.functions.getNumBounties().call() - 1
  File "/usr/local/lib/python3.6/dist-packages/web3/contract.py", line 1094, in call
    block_id = parse_block_identifier(self.web3, block_identifier)
  File "/usr/local/lib/python3.6/dist-packages/web3/contract.py", line 1400, in parse_block_identifier
    last_block = web3.eth.getBlock('latest').number
  File "/usr/local/lib/python3.6/dist-packages/web3/eth.py", line 141, in getBlock
    [block_identifier, full_transactions],
  File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 107, in request_blocking
    response = self._make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 90, in _make_request
    return request_func(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/exception_retry_request.py", line 80, in middleware
    return make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/providers/rpc.py", line 68, in make_request
    **self.get_request_kwargs()
  File "/usr/local/lib/python3.6/dist-packages/web3/utils/request.py", line 27, in make_post_request
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://rinkeby.infura.io/
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit```

Part traceback for `docker-compose exec web python3 app/manage.py sync_geth rinkeby 1 99999999999`:

```[4/2 1:00] Getting bounty 2
ERROR 2020-04-02 01:53:24,301 sync_geth 185 139917235447616 Failed to fetch github username
Traceback (most recent call last):
  File "/code/app/dashboard/management/commands/sync_geth.py", line 82, in handle
    bounty = get_bounty(bounty_enum, network)
  File "/code/app/dashboard/utils.py", line 378, in get_bounty
    issuer, contract_deadline, fulfillmentAmount, paysTokens, bountyStage, balance = standard_bounties.functions.getBounty(bounty_enum).call()
  File "/usr/local/lib/python3.6/dist-packages/web3/contract.py", line 1094, in call
    block_id = parse_block_identifier(self.web3, block_identifier)
  File "/usr/local/lib/python3.6/dist-packages/web3/contract.py", line 1400, in parse_block_identifier
    last_block = web3.eth.getBlock('latest').number
  File "/usr/local/lib/python3.6/dist-packages/web3/eth.py", line 141, in getBlock
    [block_identifier, full_transactions],
  File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 107, in request_blocking
    response = self._make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 90, in _make_request
    return request_func(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/exception_retry_request.py", line 80, in middleware
    return make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/providers/rpc.py", line 68, in make_request
    **self.get_request_kwargs()
  File "/usr/local/lib/python3.6/dist-packages/web3/utils/request.py", line 27, in make_post_request
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://rinkeby.infura.io/
ERROR 2020-04-02 01:53:24,425 sync_geth 185 139917235447616 * Exception in sync_geth => 403 Client Error: Forbidden for url: https://rinkeby.infura.io/
[4/2 1:00] Getting bounty 3
ERROR 2020-04-02 01:53:25,254 sync_geth 185 139917235447616 Failed to fetch github username
Traceback (most recent call last):
  File "/code/app/dashboard/management/commands/sync_geth.py", line 82, in handle
    bounty = get_bounty(bounty_enum, network)
  File "/code/app/dashboard/utils.py", line 378, in get_bounty
    issuer, contract_deadline, fulfillmentAmount, paysTokens, bountyStage, balance = standard_bounties.functions.getBounty(bounty_enum).call()
  File "/usr/local/lib/python3.6/dist-packages/web3/contract.py", line 1094, in call
    block_id = parse_block_identifier(self.web3, block_identifier)
  File "/usr/local/lib/python3.6/dist-packages/web3/contract.py", line 1400, in parse_block_identifier
    last_block = web3.eth.getBlock('latest').number
  File "/usr/local/lib/python3.6/dist-packages/web3/eth.py", line 141, in getBlock
    [block_identifier, full_transactions],
  File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 107, in request_blocking
    response = self._make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/manager.py", line 90, in _make_request
    return request_func(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/middleware/exception_retry_request.py", line 80, in middleware
    return make_request(method, params)
  File "/usr/local/lib/python3.6/dist-packages/web3/providers/rpc.py", line 68, in make_request
    **self.get_request_kwargs()
  File "/usr/local/lib/python3.6/dist-packages/web3/utils/request.py", line 27, in make_post_request
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://rinkeby.infura.io/
ERROR 2020-04-02 01:53:25,388 sync_geth 185 139917235447616 * Exception in sync_geth => 403 Client Error: Forbidden for url: https://rinkeby.infura.io/```

**Comment by walidmujahid** [comment]
Possibly related is the seemingly unending loop of 400 Errors from `/sync/web3/ ` when 'Transaction Processing' after submitting a bounty from localhost docker.

**Comment by walidmujahid** [comment]
Going through the bug posts on Infura's community forum, I am beginning to suspect this is could be a problem with web3.;py or a combined problem between web3.py and any recent changes with the Infura API. Or at least, it would seem the HTTP API and web3.py. I will look into this more in the morning.

**Comment by walidmujahid** [comment]
Going through the bug posts on Infura's community forum, I think the problem may lay somewehre between the HTTP API and web3.py. I will look into this more in the morning.

**Comment by owocki** [comment]
> ERROR 2020-04-02 01:53:25,388 sync_geth 185 139917235447616 * Exception in sync_geth => 403 Client Error: Forbidden for url: https://rinkeby.infura.io/```


i think that you gotta add an infura project ID a la the following to your env file

```
WEB3_HTTP_PROVIDER=https://rinkeby.infura.io/v3/API_KEY_FROM_INFURA
INFURA_USE_V3=True
INFURA_V3_PROJECT_ID=API_KEY_FROM_INFURA
```

this probably needs to be updated in the docs too, as this is a new requirement that infura is enforcing

**Comment by walidmujahid** [comment]
@owocki Testing it now.

**Comment by walidmujahid** [comment]
@owocki I have tried overriding the `WEB3_HTTP_PROVIDER` env variable, however the result is the same. I am not sure doing this is necessary either as the dashboard.utils functions already have this format. 

I did supply a custom overrride for `INFURA_V3_PROJECT_ID` for both the default ID as well as a personal Infura ID I set up to test this, however, the errors remain.

**Comment by owocki** [comment]
well the errors in your issue desc still point to `https://rinkeby.infura.io/` not `https://rinkeby.infura.io/PROJECT_ID` so i think that the ENV variable is not being recognized probably. sometimes u have to restart the container to get them recognized, or its possible that however you're instanstiating web3py isnt actually looking at the project ID.

**Comment by walidmujahid** [comment]
> well the errors in your issue desc still point to https://rinkeby.infura.io/ not https://rinkeby.infura.io/PROJECT_ID so i think that the ENV variable is not being recognized probably. 

@owocki Indeed this does seem to be the case. I just thought that the default in `app/app/settings.py:741:INFURA_V3_PROJECT_ID = env('INFURA_V3_PROJECT_ID', default='1e0a90928efe4bb78bb1eeceb8aacc27')` had been taking care of that. 

> its possible that however you're instanstiating web3py isnt actually looking at the project ID.

It is the same as in the current master. I have not touched the instantiation. Though, could it be possible that web3py v4 is the reason? I suppose I could try upgrading to v5 unless that cannot be merged into master.

**Comment by walidmujahid** [comment]
The problem may have been my use of an old .env file. I am updating it to the most recent and will see if that resolves the problem, though, there is nothing different for the INFURA variables between the version I had used and the newest versions. 

I will update this thread soon.

**Comment by walidmujahid** [comment]
Okay. So updating to the most recent local .env worked. I suspect, though I did not confirm, that the problem with the original file was the lack of the `ETHERSCAN_API_KEY` variable.

In any case, thank you for the time you put into suggesting possible solutions @owocki 

This has been resolved.
