### ISSUE TITLE
Cannot Run server - django.core.exceptions.ImproperlyConfigured: Module "django_redis.client" does not define a "DefaultClienta" class

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6384]
when running the web_web_1 container on the most recent `master`, this is what i get

```
web_1      | Traceback (most recent call last):
web_1      |   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
web_1      |     self.run()
web_1      |   File "/usr/lib/python3.6/threading.py", line 864, in run
web_1      |     self._target(*self._args, **self._kwargs)
web_1      |   File "/usr/local/lib/python3.6/dist-packages/django/utils/autoreload.py", line 54, in wrapper
web_1      |     fn(*args, **kwargs)
web_1      |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/commands/runserver.py", line 117, in inner_run
web_1      |     self.check(display_num_errors=True)
web_1      |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 390, in check
web_1      |     include_deployment_checks=include_deployment_checks,
web_1      |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 377, in _run_checks
web_1      |     return checks.run_checks(**kwargs)
web_1      |   File "/usr/local/lib/python3.6/dist-packages/django/core/checks/registry.py", line 72, in run_checks
web_1      |     new_errors = check(app_configs=app_configs)
web_1      |   File "/usr/local/lib/python3.6/dist-packages/django/core/checks/urls.py", line 13, in check_url_config
web_1      |     return check_resolver(resolver)
web_1      |   File "/usr/local/lib/python3.6/dist-packages/django/core/checks/urls.py", line 23, in check_resolver
web_1      |     return check_method()
web_1      |   File "/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py", line 398, in check
web_1      |     for pattern in self.url_patterns:
web_1      |   File "/usr/local/lib/python3.6/dist-packages/django/utils/functional.py", line 80, in __get__
web_1      |     res = instance.__dict__[self.name] = self.func(instance)
web_1      |   File "/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py", line 579, in url_patterns
web_1      |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
web_1      |   File "/usr/local/lib/python3.6/dist-packages/django/utils/functional.py", line 80, in __get__
web_1      |     res = instance.__dict__[self.name] = self.func(instance)
web_1      |   File "/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py", line 572, in urlconf_module
web_1      |     return import_module(self.urlconf_name)
web_1      |   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
web_1      |     return _bootstrap._gcd_import(name[level:], package, level)
web_1      |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
web_1      |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
web_1      |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
web_1      |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
web_1      |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
web_1      |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
web_1      |   File "/code/app/app/urls.py", line 50, in <module>
web_1      |     import perftools.views
web_1      |   File "/code/app/perftools/views.py", line 7, in <module>
web_1      |     @cache_page(60 * 60 * 24)
web_1      |   File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/cache.py", line 23, in cache_page
web_1      |     cache_timeout=timeout, cache_alias=cache, key_prefix=key_prefix
web_1      |   File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py", line 128, in _make_decorator
web_1      |     middleware = middleware_class(*m_args, **m_kwargs)
web_1      |   File "/usr/local/lib/python3.6/dist-packages/django/middleware/cache.py", line 189, in __init__
web_1      |     self.cache = caches[self.cache_alias]
web_1      |   File "/usr/local/lib/python3.6/dist-packages/django/core/cache/__init__.py", line 79, in __getitem__
web_1      |     cache = _create_cache(alias)
web_1      |   File "/usr/local/lib/python3.6/dist-packages/django/core/cache/__init__.py", line 54, in _create_cache
web_1      |     return backend_cls(location, params)
web_1      |   File "/usr/local/lib/python3.6/dist-packages/django_redis/cache.py", line 51, in __init__
web_1      |     self._client_cls = load_class(self._client_cls)
web_1      |   File "/usr/local/lib/python3.6/dist-packages/django_redis/util.py", line 34, in load_class
web_1      |     raise ImproperlyConfigured('Module "{0}" does not define a "{1}" class'.format(mod_name, klass_name))
web_1      | django.core.exceptions.ImproperlyConfigured: Module "django_redis.client" does not define a "DefaultClienta" class
```

**Comment by owocki** [comment]
i fat fingered my REDIS_URL path in my ENV and that was the root casue ..

```
REDIS_URL=rediscache://redis:6379/0?client_class=django_redis.client.DefaultClienta
```
