### ISSUE TITLE
Faucet giving 500 when submissino

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#646]
From a user on slack: HOw to get faucets , it is showing internal server error when submitting form using /faucet link

From the logs
```
Traceback (most recent call last):
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/ratelimit/decorators.py", line 30, in _wrapped
    return fn(*args, **kw)
  File "/home/ubuntu/gitcoin/coin/app/tdi/views.py", line 78, in whitepaper_new
    send_mail(settings.CONTACT_EMAIL, settings.CONTACT_EMAIL, "New Whitepaper Request", str(body))
  File "/home/ubuntu/gitcoin/coin/app/marketing/mails.py", line 69, in send_mail
    response = sg.client.mail.send.post(request_body=mail.get())
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/python_http_client/client.py", line 227, in http_request
    return Response(self._make_request(opener, request))
  File "/home/ubuntu/gitcoin/gitcoin-3/lib/python3.6/site-packages/python_http_client/client.py", line 161, in _make_request
    raise exc
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized
Internal Server Error: /whitepaper
```

**Comment by owocki** [comment]
from the console logs

```
In [2]: settings.SENDGRID_API_KEY
Out[2]: 'TODO'

```

**Comment by owocki** [comment]
@mbeacom it seems like when the env settings got carried over that this setting did not correctly make the transfer....  how can we be sure that theres no other settings that didn't transfer?

**Comment by owocki** [comment]
i just edited https://gitlab.com/Owocki/gitcoin_server/blob/master/assets/prod.env but it seems that the deploy.bash script does not work in actually updating the live environment?  did you copy/paste the prod.env file into `/home/ubuntu/gitcoin/coin/app/app/.env` ?

**Comment by owocki** [comment]
actually.. i want to reopen this until were sure no other keys were lost in xfr

**Comment by mbeacom** [comment]
@owocki I'll go through the original `settings` and `local_settings`.

**Comment by mbeacom** [comment]
@owocki I checked all entries from our original env_settings.py files against their new `.env` counterparts.  No other missing keys that I can see.

**Comment by mkosowsk** [comment]
👍🏻@mbeacom what's best practices to prevent this going forward? Have a script that does the xfr or is that overkill?

**Comment by owocki** [comment]
thx!

**Comment by owocki** [comment]
@mkosowsk it was a one time migration.. so not sure we need to make sure it doesnt happen moving forward

**Comment by owocki** [comment]
```
In [2]: settings.GITCOINBOT_APP_ID
Out[2]: ''
```

0e3dfefb49b9f11e9c6eaa6e52de6316518a45c7
