### ISSUE TITLE
Starting local docker instance fails at collecting django-autotranslate

### ISSUE THREAD

**Issue by proofoftom** [gitcoinco/web#6607]
**Describe the bug**
When attempting to start local development environment with
```
git clone https://github.com/gitcoinco/web.git
cd web
cp app/app/local.env app/app/.env
```
am getting a bit through the process but am always erroring out at:
```
Collecting django-autotranslate==1.1.0
  Downloading django-autotranslate-1.1.0.tar.gz (8.7 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-y2hhn88p/django-autotranslate/setup.py'"'"'; __file__='"'"'/tmp/pip-install-y2hhn88p/django-autotranslate/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-r3o0dtyd
         cwd: /tmp/pip-install-y2hhn88p/django-autotranslate/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-y2hhn88p/django-autotranslate/setup.py", line 25, in <module>
        requirements = [str(ir.req) for ir in install_requirements]
      File "/tmp/pip-install-y2hhn88p/django-autotranslate/setup.py", line 25, in <listcomp>
        requirements = [str(ir.req) for ir in install_requirements]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip3 install --upgrade -r test.txt' returned a non-zero code: 1
make: *** [fresh] Error 1
```
have tried running `make fresh` to no avail.

**To Reproduce**
Am following the instructions here: https://docs.gitcoin.co/mk_setup/

**Expected behavior**
No errors and a local gitcoin development environment.

**Command line:**

- OS: macOS 10.14.6
- Docker Engine: 19.03.8
- Docker Compose: 1.25.4

**Additional context**
Have had this previously set up before, so perhaps is conflicting with an old environment?

**Comment by owocki** [comment]
https://github.com/ankitpopli1891/django-autotranslate/pull/20 fixes this

**Comment by owocki** [comment]
sorry wrong link, https://github.com/ankitpopli1891/django-autotranslate/issues/24 is the issue

**Comment by proofoftom** [comment]
Fixed by changing line 38 of the Dockerfile to pin pip to version 20.0.2:
`RUN pip3 install --upgrade pip==20.0.2 setuptools wheel dumb-init pipenv`
